/* In this we find out different measures by categories ( dimension ) */

-- Find total customers by countries
Select country,count(customer_key) as total_customers
from dim_customers
group by country
order by total_customers desc;


-- Find total customers by gender

Select gender,count(customer_key) as total_customers
from dim_customers
group by gender
order by total_customers desc;

-- Find total products by category

Select category, count(product_key) as total_products
from dim_products
group by category
order by total_products desc;

-- What is the average costs in each category?

Select category, round(avg(product_cost),2) as avg_cost
from dim_products
group by category
order by avg_cost desc;

-- What is the total revenue generated for each category?
Select dim.category,sum(fact.sales_amount) as total_revenue
from fact_sales as fact
Left join dim_products as dim
on fact.product_key = dim.product_key
group by dim.category
order by total_revenue desc;

Select distinct dim.category
from fact_sales as fact
Left join dim_products as dim
on fact.product_key = dim.product_key;

-- Find total revenue is generated by each customer

Select 
dim.customer_key,dim.first_name,dim.last_name,
sum(fact.sales_amount) as total_revenue
from fact_sales as fact
Left join dim_customers as dim
on fact.customer_key = dim.customer_key
group by dim.customer_key,dim.first_name,dim.last_name
order by total_revenue desc;

-- What is the distribution of sold items across countries?

Select country, sum(quantity) as sold_items 
from fact_sales as f
left join dim_customers as d
on f.customer_key = d.customer_key
group by d.country
order by sold_items desc;
